---
confluent_repo_version: 5.5
confluent_package_version: 5.5.1
confluent_full_package_version: "{{ confluent_package_version + '-1' }}"
confluent_package_redhat_suffix: "{{ '-' + confluent_full_package_version if confluent_full_package_version != '' else ''}}"
control_center_service_name: confluent-control-center
kafka_broker_main_package: confluent-kafka-2.12
control_center_default_internal_replication_factor: "{{ [ groups['kafka_broker'] | length, 3 ] | min }}"
control_center_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ kafka_broker_main_package }}"
  - confluent-rebalancer
  - confluent-control-center-fe
  - confluent-control-center
control_center_default_user: cp-control-center
control_center_default_group: confluent
control_center:
  appender_log_path: /var/log/confluent/control-center/
  c3appender_log_name: control-center.log
  c3appender_max_log_files: 10
  c3appender_log_file_size: 100MB
  streamsappender_log_name: control-center-streams.log
  streamsappender_max_log_files: 10
  streamsappender_log_file_size: 100MB
  kafkaappender_log_name: control-center-kafka.log
  kafkaappender_max_log_files: 10
  kafkaappender_log_file_size: 100MB
  properties:
    confluent.controlcenter.streams.num.stream.threads: 8
    confluent.controlcenter.data.dir: /var/lib/confluent/control-center
    confluent.controlcenter.ksql.enable: 'true'
    confluent.controlcenter.schema.registry.enable: 'true'
    confluent.controlcenter.internal.topics.replication: "{{control_center_default_internal_replication_factor}}"
    confluent.metrics.topic.replication: "{{control_center_default_internal_replication_factor}}"
    confluent.monitoring.interceptor.topic.replication: "{{control_center_default_internal_replication_factor}}"
    confluent.controlcenter.command.topic.replication: "{{control_center_default_internal_replication_factor}}"
  config_file: /etc/confluent-control-center/control-center-production.properties
  systemd_file: /usr/lib/systemd/system/{{control_center_service_name}}.service
  systemd_override: /etc/systemd/system/{{control_center_service_name}}.service.d/override.conf
  log4j_file: /etc/confluent-control-center/control-center_log4j.properties

# Control Center Variables
control_center_user: "{{control_center_default_user}}"
control_center_group: "{{control_center_default_group}}"
control_center_port: 9021
control_center_listener_hostname: "0.0.0.0"
control_center_ssl_enabled: "{{ssl_enabled}}"
control_center_ssl_mutual_auth_enabled: "{{ ssl_mutual_auth_enabled }}"
control_center_http_protocol: "{{ 'https' if control_center_ssl_enabled|bool else 'http' }}"
control_center_truststore_path: "/var/ssl/private/control_center.truststore.jks"
control_center_keystore_path: "/var/ssl/private/control_center.keystore.jks"
control_center_truststore_storepass: "{{ ssl_truststore_password if ssl_provided_keystore_and_truststore|bool else 'confluenttruststorepass'}}"
control_center_keystore_storepass: "{{ ssl_keystore_store_password if ssl_provided_keystore_and_truststore|bool else 'confluentkeystorestorepass'}}"
control_center_keystore_keypass: "{{ ssl_keystore_key_password if ssl_provided_keystore_and_truststore|bool else control_center_keystore_storepass }}"
control_center_ca_cert_path: "/var/ssl/private/ca.crt"
control_center_cert_path: "/var/ssl/private/control_center.crt"
control_center_key_path: "/var/ssl/private/control_center.key"
control_center_kafka_listener_name: internal

