---
# Install Packages
- name: Install the Kafka Rest Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{kafka_rest_packages}}"
  when: ansible_os_family == "RedHat"

# Configure environment
- name: Create Kafka Rest Group
  group:
    name: "{{kafka_rest_group}}"

- name: Create Kafka Rest User
  user:
    name: "{{kafka_rest_user}}"
    comment: "Kafka REST User"
    system: true
    group: "{{kafka_rest_group}}"
- name: Start Kafka Rest Service
  systemd:
    name: "{{kafka_rest_service_name}}"
    enabled: true
    state: started

- name: Create Logs Directory
  file:
    path: "{{kafka_rest.appender_log_path}}"
    state: directory
    owner: "{{kafka_rest_user}}"
    group: "{{kafka_rest_group}}"
    mode: 0750

- name: Start Kafka Rest Service
  systemd:
    name: "{{kafka_rest_service_name}}"
    enabled: true
    state: started
