---
# Install Packages
- name: Install the Schema Registry Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{schema_registry_packages}}"
  when: ansible_os_family == "RedHat"

# Configure environment
- name: Schema Registry Group
  group:
    name: "{{schema_registry_group}}"

- name: Schema Registry User
  user:
    name: "{{schema_registry_user}}"
    comment: "Schema Registry User"
    system: true
    group: "{{schema_registry_group}}"

- name: Create Logs Directory
  file:
    path: "{{schema_registry.appender_log_path}}"
    state: directory
    group: "{{schema_registry_group}}"
    owner: "{{schema_registry_user}}"
    mode: 0750

- name: Start Schema Registry Service
  systemd:
    name: "{{schema_registry_service_name}}"
    enabled: true
    state: started
